server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  thymeleaf:
    cache: false

logging:
  level:
    org.springframework: INFO

tesseract:
  datapath: tessdata  # Path to the folder containing traineddata files